### PR TITLE
bugfix: NamedTemporaryFile can't be opened twice

### PR DESCRIPTION
**Pull request by hredestig**
..on Windows we get
```
self = <optlang.glpk_interface.Model object at 0x09695550>
    def _glpk_representation(self):
        with tempfile.NamedTemporaryFile(suffix=".glpk", delete=True) as tmp_file:
            tmp_file_name = tmp_file.name
            glp_write_prob(self.problem, 0, tmp_file_name)
>           with open(tmp_file_name) as tmp_file:
E           IOError: [Errno 13] Permission denied: 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\tmptwsotv.glpk'
```
solution found in

http://stackoverflow.com/questions/23212435/permission-denied-to-write-to-my-temporary-file

### CODE REVIEW

**Comment by hredestig** [comment]
best to try this somewhere that has gurobi installed as well before merging
also not sure why codecov is complaining..

**Comment by hredestig** [comment]
I wrongly assumed it only concerned write-mode files, I tested now on windows and don't get permission errors anymore but get some other seemingly unrelated issue that I don't see on mac:
```
======================================================================
ERROR: test_add_non_cplex_conform_variable (optlang.tests.test_glpk_interface.ModelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\optlang\optlang\tests\test_glpk_interface.py", line 155, in test_add_non_cplex_conform_variable
    var_from_pickle = repickled.variables['12x!!@#5_3']
  File "C:\projects\optlang\optlang\container.py", line 84, in __getitem__
    return self._dict[item]  # Treat item as key (name)
KeyError: '12x!!@#5_3'
======================================================================
FAIL: test_copy (optlang.tests.test_glpk_interface.ModelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\optlang\optlang\tests\abstract_test_cases.py", line 252, in test_copy
    self.assertAlmostEqual(value, model_copy.objective.value)
AssertionError: 0.8739215069684303 != 0.0 within 7 places
    '0.8739215069684303 != 0.0 within 7 places' = self._formatMessage('0.8739215069684303 != 0.0 within 7 places', '0.8739215069684303 != 0.0 within 7 places')
>>  raise self.failureException('0.8739215069684303 != 0.0 within 7 places')
    
======================================================================
FAIL: test_deepcopy (optlang.tests.test_glpk_interface.ModelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\optlang\optlang\tests\abstract_test_cases.py", line 265, in test_deepcopy
    self.assertAlmostEqual(value, model_copy.objective.value)
AssertionError: 0.8739215069684303 != 0.0 within 7 places
    '0.8739215069684303 != 0.0 within 7 places' = self._formatMessage('0.8739215069684303 != 0.0 within 7 places', '0.8739215069684303 != 0.0 within 7 places')
>>  raise self.failureException('0.8739215069684303 != 0.0 within 7 places')
    
======================================================================
FAIL: test_pickle_ability (optlang.tests.test_glpk_interface.ModelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\optlang\optlang\tests\test_glpk_interface.py", line 125, in test_pickle_ability
    self.assertAlmostEqual(value, from_pickle.objective.value)
AssertionError: 0.8739215069684303 != 0.0 within 7 places
    '0.8739215069684303 != 0.0 within 7 places' = self._formatMessage('0.8739215069684303 != 0.0 within 7 places', '0.8739215069684303 != 0.0 within 7 places')
>>  raise self.failureException('0.8739215069684303 != 0.0 within 7 places')
    
----------------------------------------------------------------------
Ran 405 tests in 165.391s
```
perhaps one should enable appveyor testing for optlang as well proper..

**Comment by hredestig** [comment]
this now adds a basic appveyor config as well, I guess that's the safer that way. It doesn't pass the `test_add_non_cplex_conform_variable` test though as indicated above, @KristianJensen perhaps you can have a look - finish this?

**Comment by KristianJensen** [comment]
@hredestig Does `test_add_non_cplex_conform_variable` fail on windows? Everything passes when I run the tests on mac

**Comment by hredestig** [comment]
All of those tests fail on windows yes..

https://ci.appveyor.com/project/hredestig/optlang/build/job/l58bci2o51ssd6lx

**Comment by KristianJensen** [comment]
@hredestig It looks like everything is passing now, right?

**Pull request merged**
