### PR TITLE
adding simple example using numpy linear algebra

### PR DESCRIPTION
**Pull request by pstjohn**
Is this helpful? I think its nice to see that optlang symbolics play nicely with numpy datatypes. 
Is there a better way to create a vector of symbols?

### CODE REVIEW

**Comment by phantomas1234** [comment]
Sympy itself has linear algebra functions but it is indeed cool to see that numpy works just as well! Should we make this part of the docs? I know that you requested better docs in the past and I agree that we should improve the optlang docs in general.

**Comment by pstjohn** [comment]
It could certainly just form a note in the documentation. The sympy vectors would also be neat to see how you could use those to construct constraints.

**Comment by KristianJensen** [comment]
Yes this is a really nice feature that I've also used a couple of times. If you fix the flake8 complaint(s) then I'll happily merge this. I think examples like this are a great way to showcase what the package can do

**Comment by pstjohn** [comment]
>  If you fix the flake8 complaint(s)
Sorry, definitely meant to do that but ended up forgetting... 
Thanks doing that!

**Pull request merged**
