### PR TITLE
fix: make releases from only one Python version

### PR DESCRIPTION
**Pull request by Midnighter**
* Add Python 3.6 to tested versions.
* Abort testing as soon as one test fails (`fast_finish`).
* Add the Python version to the conditions such that only one deployment is attempted.

### CODE REVIEW

**Comment by Midnighter** [comment]
I'm not sure that releasing the wheel on GitHub is really necessary. PyPi is the place for that.

**Comment by Midnighter** [comment]
Additionally, I'm not sure the condition for installing CPLEX is still up to date (AFAIK 12.7.1 works exactly for Python 3.5).

**Comment by Midnighter** [comment]
And I don't think installing swig etc. is required any longer since swiglpk comes packaged in a wheel.

**Comment by KristianJensen** [comment]
Great! I agree that installing swig should not be necessary. Neither should glpk-utils or libglpk I guess. Cplex 12.7.1 does indeed work with python 3.5, but the cplex that is installed with the current secret link is an older version that works for 3.4. It would be nice to update the cplex version and drop 3.4 testing.

Out of curiosity, which part of your changes makes sure that only one job tries to deploy?

**Comment by KristianJensen** [comment]
For the last couple of releases, no wheel has been uploaded to pypi, only the source. Do you know why this would happen?

**Comment by Midnighter** [comment]
> Great! I agree that installing swig should not be necessary. Neither should glpk-utils or libglpk I guess. Cplex 12.7.1 does indeed work with python 3.5, but the cplex that is installed with the current secret link is an older version that works for 3.4. It would be nice to update the cplex version and drop 3.4 testing.

I will remove the dependencies but leave CPLEX as it is for now.

> Ah I guess it's the on: python: 3.6 part. There will be two 3.6 jobs though, with and without symengine. Won't both of these try to deploy?

You're right. I will add a further condition.

> For the last couple of releases, no wheel has been uploaded to pypi, only the source. Do you know why this would happen?

Since I add `distributions: sdist bdist_wheel` that's hopefully solved.

**Pull request merged**
